- name: Ansible Docker PUSH step
  hosts: localhost
  tasks:
    - name: Log into Docker Hub and force re-authorization
      docker_login:
        username: danroz
        password: Dan8101995!
        email: danroz3@gmail.com
        reauthorize: yes
        
    - name: push an image
      docker_image:
        name: danroz/time-tracker
        tag: latest
        push: yes
        
    - name: push an image to the local Nexus registry
      docker_image:
        name: danroz/time-tracker
        repository: 127.0.0.1:8082/time-tracker
        tag: latest
        push: yes
