apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-tracker
  labels:
    app: time-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-tracker
  template:
    metadata:
      labels:
        app: time-tracker
    spec:
      containers:
      - name: time-tracker
        image: danroz/time-tracker:latest
        ports:
        - containerPort: 8080
